"""add US1 models health nutrition conversation

Revision ID: 7f0ce16e469b
Revises: 9d200e74902b
Create Date: 2026-03-07 23:03:51.523689

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f0ce16e469b"
down_revision: str | Sequence[str] | None = "9d200e74902b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversation_state",
        sa.Column("user_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("last_response_id", sa.String(length=200), nullable=True),
        sa.Column("turn_count", sa.Integer(), nullable=False),
        sa.Column("session_summary", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["family_member.id"],
            name=op.f("fk_conversation_state_user_id_family_member"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_conversation_state")),
    )
    op.create_table(
        "diet_record",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pet_id", sa.Integer(), nullable=False),
        sa.Column("food_brand", sa.String(length=200), nullable=False),
        sa.Column("food_type", sa.String(length=50), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("recorded_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pet_id"],
            ["pet.id"],
            name=op.f("fk_diet_record_pet_id_pet"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by"],
            ["family_member.id"],
            name=op.f("fk_diet_record_recorded_by_family_member"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_diet_record")),
    )
    op.create_index(
        "ix_diet_record_pet_end", "diet_record", ["pet_id", "end_date"], unique=False
    )
    op.create_table(
        "emergency_profile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pet_id", sa.Integer(), nullable=False),
        sa.Column("allergies", sa.Text(), nullable=True),
        sa.Column("chronic_conditions", sa.Text(), nullable=True),
        sa.Column("vet_contact", sa.Text(), nullable=True),
        sa.Column("blood_type", sa.String(length=20), nullable=True),
        sa.Column("rabies_vaccination_date", sa.Date(), nullable=True),
        sa.Column(
            "latest_weight_snapshot", sa.Numeric(precision=5, scale=2), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["pet_id"],
            ["pet.id"],
            name=op.f("fk_emergency_profile_pet_id_pet"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_emergency_profile")),
        sa.UniqueConstraint("pet_id", name=op.f("uq_emergency_profile_pet_id")),
    )
    op.create_table(
        "feeding_entry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pet_id", sa.Integer(), nullable=False),
        sa.Column("fed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("food_description", sa.String(length=300), nullable=False),
        sa.Column("portion_size", sa.String(length=50), nullable=True),
        sa.Column("recorded_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pet_id"],
            ["pet.id"],
            name=op.f("fk_feeding_entry_pet_id_pet"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by"],
            ["family_member.id"],
            name=op.f("fk_feeding_entry_recorded_by_family_member"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feeding_entry")),
    )
    op.create_index(
        "ix_feeding_entry_pet_fed", "feeding_entry", ["pet_id", "fed_at"], unique=False
    )
    op.create_table(
        "medical_record",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pet_id", sa.Integer(), nullable=False),
        sa.Column("record_type", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("resolved_date", sa.Date(), nullable=True),
        sa.Column("vet_name", sa.String(length=200), nullable=True),
        sa.Column("recorded_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pet_id"],
            ["pet.id"],
            name=op.f("fk_medical_record_pet_id_pet"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by"],
            ["family_member.id"],
            name=op.f("fk_medical_record_recorded_by_family_member"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_medical_record")),
    )
    op.create_index(
        "ix_medical_record_pet_date", "medical_record", ["pet_id", "date"], unique=False
    )
    op.create_index(
        "ix_medical_record_pet_type",
        "medical_record",
        ["pet_id", "record_type"],
        unique=False,
    )
    op.create_table(
        "medication",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pet_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("dosage", sa.String(length=100), nullable=True),
        sa.Column("frequency", sa.String(length=100), nullable=True),
        sa.Column("frequency_days", sa.Integer(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("last_given_date", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("recorded_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pet_id"],
            ["pet.id"],
            name=op.f("fk_medication_pet_id_pet"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by"],
            ["family_member.id"],
            name=op.f("fk_medication_recorded_by_family_member"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_medication")),
    )
    op.create_index(
        "ix_medication_pet_active", "medication", ["pet_id", "is_active"], unique=False
    )
    op.create_table(
        "note",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pet_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("recorded_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pet_id"], ["pet.id"], name=op.f("fk_note_pet_id_pet"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by"],
            ["family_member.id"],
            name=op.f("fk_note_recorded_by_family_member"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_note")),
    )
    op.create_index(
        "ix_note_pet_created", "note", ["pet_id", "created_at"], unique=False
    )
    op.create_table(
        "vaccination",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pet_id", sa.Integer(), nullable=False),
        sa.Column("vaccine_name", sa.String(length=200), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("next_date", sa.Date(), nullable=True),
        sa.Column("vet_name", sa.String(length=200), nullable=True),
        sa.Column("batch_number", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("recorded_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pet_id"],
            ["pet.id"],
            name=op.f("fk_vaccination_pet_id_pet"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by"],
            ["family_member.id"],
            name=op.f("fk_vaccination_recorded_by_family_member"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vaccination")),
    )
    op.create_index(
        "ix_vaccination_pet_date", "vaccination", ["pet_id", "date"], unique=False
    )
    op.create_index(
        "ix_vaccination_pet_next_date",
        "vaccination",
        ["pet_id", "next_date"],
        unique=False,
    )
    op.create_table(
        "weight_record",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pet_id", sa.Integer(), nullable=False),
        sa.Column("weight_kg", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("measured_at", sa.Date(), nullable=False),
        sa.Column("recorded_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pet_id"],
            ["pet.id"],
            name=op.f("fk_weight_record_pet_id_pet"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by"],
            ["family_member.id"],
            name=op.f("fk_weight_record_recorded_by_family_member"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_weight_record")),
    )
    op.create_index(
        "ix_weight_record_pet_measured",
        "weight_record",
        ["pet_id", "measured_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_weight_record_pet_measured", table_name="weight_record")
    op.drop_table("weight_record")
    op.drop_index("ix_vaccination_pet_next_date", table_name="vaccination")
    op.drop_index("ix_vaccination_pet_date", table_name="vaccination")
    op.drop_table("vaccination")
    op.drop_index("ix_note_pet_created", table_name="note")
    op.drop_table("note")
    op.drop_index("ix_medication_pet_active", table_name="medication")
    op.drop_table("medication")
    op.drop_index("ix_medical_record_pet_type", table_name="medical_record")
    op.drop_index("ix_medical_record_pet_date", table_name="medical_record")
    op.drop_table("medical_record")
    op.drop_index("ix_feeding_entry_pet_fed", table_name="feeding_entry")
    op.drop_table("feeding_entry")
    op.drop_table("emergency_profile")
    op.drop_index("ix_diet_record_pet_end", table_name="diet_record")
    op.drop_table("diet_record")
    op.drop_table("conversation_state")
    # ### end Alembic commands ###
