"""initial_phase2_models

Revision ID: 9d200e74902b
Revises:
Create Date: 2026-03-07 18:03:30.209038

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9d200e74902b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "family",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "singleton_key",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_family")),
        sa.UniqueConstraint("singleton_key", name="uq_family_singleton"),
    )
    op.create_table(
        "family_member",
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=True),
        sa.Column("is_authorized", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("family_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["family.id"],
            name=op.f("fk_family_member_family_id_family"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_family_member")),
    )
    op.create_table(
        "family_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("family_id", sa.Integer(), nullable=False),
        sa.Column("timezone", sa.String(length=50), nullable=False),
        sa.Column("date_locale", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["family.id"],
            name=op.f("fk_family_settings_family_id_family"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_family_settings")),
        sa.UniqueConstraint("family_id", name=op.f("uq_family_settings_family_id")),
    )
    op.create_table(
        "oauth_credential",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("family_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("access_token_enc", sa.Text(), nullable=False),
        sa.Column("refresh_token_enc", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["family.id"],
            name=op.f("fk_oauth_credential_family_id_family"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_oauth_credential")),
        sa.UniqueConstraint(
            "family_id", "provider", name=op.f("uq_oauth_credential_family_id")
        ),
    )
    op.create_table(
        "change_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("actor_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("diff_json", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["family_member.id"],
            name=op.f("fk_change_log_actor_id_family_member"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_change_log")),
    )
    op.create_index("ix_changelog_actor", "change_log", ["actor_id"], unique=False)
    op.create_index(
        "ix_changelog_changed_at", "change_log", ["changed_at"], unique=False
    )
    op.create_index(
        "ix_changelog_entity", "change_log", ["entity_type", "entity_id"], unique=False
    )
    op.create_table(
        "family_invite",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("family_id", sa.Integer(), nullable=False),
        sa.Column("invite_code", sa.String(length=50), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("used_by", sa.BigInteger(), nullable=True),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["family_member.id"],
            name=op.f("fk_family_invite_created_by_family_member"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["family.id"],
            name=op.f("fk_family_invite_family_id_family"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["used_by"],
            ["family_member.id"],
            name=op.f("fk_family_invite_used_by_family_member"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_family_invite")),
        sa.UniqueConstraint("invite_code", name=op.f("uq_family_invite_invite_code")),
    )
    op.create_table(
        "pet",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("species", sa.String(length=50), nullable=False),
        sa.Column("breed", sa.String(length=100), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("gender", sa.String(length=10), nullable=True),
        sa.Column("origin_story", sa.Text(), nullable=True),
        sa.Column("blood_type", sa.String(length=20), nullable=True),
        sa.Column("chip_number", sa.String(length=50), nullable=True),
        sa.Column("vet_contact", sa.Text(), nullable=True),
        sa.Column("is_neutered", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("family_id", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["family_member.id"],
            name=op.f("fk_pet_created_by_family_member"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["family.id"],
            name=op.f("fk_pet_family_id_family"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pet")),
    )
    op.create_table(
        "family_pet",
        sa.Column("family_member_id", sa.BigInteger(), nullable=False),
        sa.Column("pet_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["family_member_id"],
            ["family_member.id"],
            name=op.f("fk_family_pet_family_member_id_family_member"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["pet_id"],
            ["pet.id"],
            name=op.f("fk_family_pet_pet_id_pet"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "family_member_id", "pet_id", name=op.f("pk_family_pet")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("family_pet")
    op.drop_table("pet")
    op.drop_table("family_invite")
    op.drop_index("ix_changelog_entity", table_name="change_log")
    op.drop_index("ix_changelog_changed_at", table_name="change_log")
    op.drop_index("ix_changelog_actor", table_name="change_log")
    op.drop_table("change_log")
    op.drop_table("oauth_credential")
    op.drop_table("family_settings")
    op.drop_table("family_member")
    op.drop_table("family")
    # ### end Alembic commands ###
